### ISSUE TITLE
SELinux issues with shell

### ISSUE THREAD

**Issue by afbjorklund** [boot2podman/boot2podman-fedora-iso#1]
Seems like /bin/bash has gone "missing", so the `tc` user cannot log in.

Looks like this is a known issue with the livecd-creator tools, unfortunately.

**Comment by afbjorklund** [comment]
Fixed in db0edbd8faef611eaf78e40881dfd5c15bea2c57

**Comment by afbjorklund** [comment]
Oops, wrong issue number (xfsprogs)

**Comment by Conan-Kudo** [comment]
@afbjorklund I did fix this issue with livecd-tools v26.1...

**Comment by afbjorklund** [comment]
Good, then the SELinux workaround can be removed... Think it (fc28) had 0.25.6 ?

**Comment by Conan-Kudo** [comment]
It's been in Fedora 28 for the last week: https://bodhi.fedoraproject.org/updates/FEDORA-2018-7eb5688a2f

It's also in Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2018-82f85b0db9

**Comment by afbjorklund** [comment]
The old ISO was built on Dec 7, so missed it
